[theme]
base = "light"
primaryColor = "#C94131"
backgroundColor = "#F4EFE6"
secondaryBackgroundColor = "#FFFDF9"
textColor = "#18211F"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
