[theme]
base = "light"
primaryColor = "#CF3F2F"
backgroundColor = "#F4EFE6"
secondaryBackgroundColor = "#FFFDF9"
textColor = "#17201E"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
